services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: __CONTAINER_NAME__-client
    image: __CONTAINER_NAME__-client
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    networks:
      - __NETWORK__

networks:
  __NETWORK__:
    driver: bridge
    external: true
