services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tarico.site
    image: $CONTAINER_NAME
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    networks:
      - $NETWORK

networks:
  $NETWORK:
    driver: bridge
    external: true
    # driver_opts:
    #   com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
