services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tarico.site
    image: $CONTAINER_NAME
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
