services:
  # Service de l'application NestJS
  app:
    build:
      context: . # Chemin vers le répertoire contenant votre Dockerfile et le code source
      dockerfile: Dockerfile
    container_name: __CONTAINER_NAME__-api
    image: __CONTAINER_NAME__-api
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db # Assure que le service de base de données démarre avant l'application
    networks:
      - __NETWORK__

  # Service de la base de données PostgreSQL
  db:
    image: postgres:16 # Utilisez une version de Postgres qui vous convient
    container_name: tarico-form-v1-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}"
    volumes:
      - __VOLUME__-db:/var/lib/postgresql/data
    networks:
      - __NETWORK__

volumes:
  __VOLUME__-db:

networks:
  __NETWORK__:
    driver: bridge
    external: true
